services:
  app:
    build:
      context: backend
    develop:
      watch:
        - action: sync+restart
          path: ./backend
          target: /app

        - action: rebuild
          path: ./backend/go.mod
      
    env_file:
      - backend/.env
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: postgres:17
    env_file:
      - backend/.env

    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pg-admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@abc.com
      - PGADMIN_DEFAULT_PASSWORD=test
      - GUNICORN_ACCESS_LOGFILE=/dev/null   # kills the request-log spam
      - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=30 # optional: app 
    
    ports:
      - 8080:80
    depends_on:
      - db

volumes:
  postgres_data: